service: Serverless-POC # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  versionLambda: false
  stage: ${opt:stage, 'alpha'}
  region: ap-south-1
  apiName: Serverless-POC
  # environment:
  #   sqs1:
  #     Ref: MessagesQueue
  #   sqs2:
  #     Ref: MessagesQueue1
custom:
  stage: ${opt:stage, 'alpha'}
  API: ${self:service}
# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  # Create-User:
  - ${file(./services/Create-User/Create-User.yml)}
  # Get-Data:
  - ${file(./services/Get-Data/Get-Data.yml)}
  # Put-Data:
  - ${file(./services/Put-Data/Put-Data.yml)}
  # lambda-integration:
  - ${file(./services/lambda-integration/lambda-integration.yml)}
  # utility
  - ${file(./services/utility/utility.yml)}
  # lambda-invoke
  - ${file(./services/lambda-invoke/lambda-invoke.yml)}
  # sqs-msg-sender
  - ${file(./services/sqs-msg-sender/sqs-msg-sender.yml)}
  # sqs-msg-receiver
  - ${file(./services/sqs-msg-receiver/sqs-msg-receiver.yml)}

# resources:
#   Resources:
#     MessagesQueue:
#       Type: AWS::SQS::Queue
#       Properties: 
#         QueueName: "SampleQueue-POC"
#     MessagesQueue1:
#       Type: AWS::SQS::Queue
#       Properties: 
#         QueueName: "SampleQueue-POC-1"